version: '3'

services:

  proxy:
    container_name: nginx
    tty: true
    #entrypoint: dockerize -wait tcp://app:3000 -timeout 30s docker-entrypoint.sh
    build:
      context: proxy
    networks:
      - people-network
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: app
    networks: 
    - people-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - people-network

  

networks:
  people-network:
    driver: bridge